name: Auto-update Caddy version

on:
  schedule:
    - cron: '17 9 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo # had to split this nonsense into more nonsense https://github.com/nektos/act/issues/678#issuecomment-1693751996
        run: git clone https://github.com/amarevite/docker-caddy-porkbun-cachehandler.git

      - name: Checkout repo
        run: git checkout ${{ steps.repository.outputs.tag }}
        # working-directory: docker-caddy-porkbun-cachehandler

      - name: list all files
        shell: bash
        run: tree "${GITHUB_WORKSPACE}/scripts/"
        
      # - name: list script
      #   shell: bash
      #   run: ls "${GITHUB_WORKSPACE}/scripts/caddy-update.sh"

      - name: Run script
        id: caddy-update
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/scripts/caddy-update.sh"

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "Dockerfile"
          default_author: user_info
          message: "Update Caddy to ${{ steps.caddy-update.outputs.LATEST_CADDY_VERSION }}"
